### ISSUE TITLE
Interactable object

### ISSUE THREAD

**Issue by sgn-fade** [sgn-fade/pinky_project#147]
Нужно создать компонент который можно повесить на обьекты для взаимодействия, например терминал, сундук, дроп и тд. Смотреть на функционал можно с двух сторон ItemDrop.cs и modules_drop.gd это два варианта имеют место быть, но ничего не мешает придумать что то новое. 
Компонент должен вешаться на обьект и давать сигналы когда в области игрок и нажал кнопку взаимодействия, это поможет убрать дублирование кода. Компонент можно представить в виде области для взаимодействия ( только в его сцене не нужно определять колизию., это должен сделать пользователь области)

**Comment by AndrasteCries** [comment]
Нужно повесить это все на другие обьекты с которыми могут быть интеракты
